site_name: emakefun文档中心
site_url: https://emakefun.com
site_author: emakefun document team
repo_url: https://github.com/mkdocs/mkdocs/

nav:
    - 首页: index.md
    - MicroBit积木: micro_bit/micro_bit.md
    - Arduino可编程产品: arduino/arduino.md
    - 开源硬件: open_source_hardware/open_source_hardware.md
    - MagicBlock: magicblock/magicblock.md
theme:
    name: 'readthedocs'