
site_name: emakefun文档中心
site_url: https://emakefun.com
site_author: emakefun document team
site_description: 深圳易创空间科技有限公司产品资料文档中心
copyright: emakefun copyright 2017-2022
repo_name: 'Github'
repo_url: https://github.com/emakefun/emakefun-docs

theme:
   name: 'mkdocs'
   custom_dir: 'custom_theme'
   language: 'cn'

   logo: 'url(images/favicon.jpg)'
   palette:
     primary: 'Teal'
     accent: 'Pink'

extra:
  search:
    language: 'jp'


nav:
    - 首页: index.md
    - 传感器/配件:
      - 总览: sensors/index.md
      - 基础模块:
        - 按键模块: sensors/base_model/button.md
        - 触摸模块: sensors/base_model/touch.md
        - 碰触开关模块: sensors/base_model/collision.md
        - 旋转电位器模块: sensors/base_model/rotaryPotentiometer.md
        - 旋转编码器模块: sensors/base_model/rotaryEncoder.md
        - 触摸钢琴模块: sensors/base_model/touchPiano.md
        - 滑动电阻器模块: sensors/base_model/slidePotentiometer.md
        - 摇杆模块: sensors/base_model/rocker.md
        - 4x4矩阵键盘模块: sensors/base_model/4x4MatrixKeyboardModel.md
        - PH2.0摇杆模块: sensors/base_model/joystick_handle.md
      - 传感器: 
        - 声音传感器: sensors/sensors/voiceSensor.md
        - 光敏传感器: sensors/sensors/photosensitiveSensor.md
        - 热敏传感器: sensors/sensors/thermalSensor.md
        - 火焰传感器: sensors/sensors/flameSensor.md
        - 土壤湿度传感器: sensors/sensors/soilMoistureSensor.md
        - 雨滴传感器: sensors/sensors/waterDropletsSensor.md
        - 水深传感器: sensors/sensors/waterDepthSensor.md
        - 温湿度传感器: sensors/sensors/temperatureAndHumiditySensor.md
        - 温度DS18B20传感器: sensors/sensors/ds18B20Sensor.md
        - 气体传感器: sensors/sensors/MQ4Sensor.md
        - 人体热释电传感器: sensors/sensors/bodySensor.md
        - 红外循迹模块传感器: sensors/sensors/trackingSensor.md
        - 磁簧开关传感器: sensors/sensors/magneticSwitchSensor.md
        - 灰度传感器: sensors/sensors/grayscaleSensor.md
        - 震动传感器: sensors/sensors/shockSensor.md
        - 倾斜传感器: sensors/sensors/tiltSwitchSensor.md
        - 气压传感器: sensors/sensors/airpressure.md
        - 超声波传感器: sensors/sensors/ultrasonicSensor.md
        - RGB超声波传感器: sensors/sensors/rgbUltrasonicSensor.md

      - 执行器: 
        - 有源蜂鸣器模块: sensors/actuators/buzzerModel.md
        - 无源蜂鸣器模块: sensors/actuators/passiveBuzzerModel.md
        - 直流电机模块: sensors/actuators/motorModel.md
        - 继电器模块: sensors/actuators/relayModel.md
        - 激光发射模块: sensors/actuators/laserEmissionModel.md
        - 振动马达: sensors/actuators/Vibration motor module.md
        - 大电机风扇模块: sensors/actuators/High power motor module.md
        - 声音输出模块: sensors/actuators/Big Speaker Module.md
        - 舵机模块: sensors/actuators/servoModel.md
        - 双路电机驱动模块: sensors/actuators/highSpeedMiniMotorDriveBoardModel.md
        - 普通红外遥控器模块: sensors/actuators/IRRemoteControlModel.md
        - emakefun红外遥控器模块: sensors/actuators/emakefunIRRemoteControlModel.md
    
      - 显示器: 
        - LED灯: sensors/shows/LED.md
        - 1602LCD显示屏: sensors/shows/LCD1602.md
        - TM1650四位数码管: sensors/shows/TM1650.md
        - TM1637四位时钟数码管: sensors/shows/TM1637.md
        - 8x8点阵屏: sensors/shows/8x8LedDisplay.md
        - 交通灯: sensors/shows/trafficLights.md
        - RGB三色灯: sensors/shows/RGB.md
        - WS2812B-RGB灯环: sensors/shows/RGBRing.md
      - 通信模块:
        - 红外发射模块: sensors/actuators/infraredEmissionModel.md
        - 红外接收模块: sensors/actuators/irReceiverModel.md
      - 智能模块:
        - 颜色识别: sensors/smart_module/color recognition.md
        - 指南针传感器: sensors/smart_module/compass.md
        - DS1302传感器: sensors/smart_module/ds1302_rtc.md
        - MPU6050六轴陀螺仪: sensors/smart_module/mpu6050.md
        - 手势传感器: sensors/smart_module/gestureRecognitionSensor.md
        - LD3320语音识别模块: sensors/smart_module/ld3320.md
        - MPU6050六轴陀螺仪: sensors/smart_module/mpu6050Sensor.md
        - MP3播放模块: sensors/smart_module/mp3.md
        - MQTT物联网模块: sensors/smart_module/esp8266_mqtt.md
      
      - 配件: micro_bit/IObit.md
    - Micro:bit产品:
      - Micro:bit主板介绍: micro_bit/microbit.md
      - Micro:bit编程介绍: micro_bit/microbit_code.md
      - IO:bit: micro_bit/IObit.md
      - Sensor:bit: micro_bit/sensorbit.md
      - Magic:bit: micro_bit/magicbit.md
      - Motor:bit: micro_bit/motorbit.md
      - Magic:bit四合一小车: micro_bit/FourInOneCar.md
      - Magic:bit麦轮小车: micro_bit/WheatwheelCar.md
    - Arduino可编程产品: 
      - Arduino主板介绍: arduino/Hummerbot2.md
      - Hummerbot: arduino/Hummerbot2.md
      - Hummerbot图形化编程: arduino/Hummerbot.md
      - Happybot: arduino/Happybot.md
      - MirageTank: arduino/MirageTank.md
      - PantherTank: arduino/PantherTank.md
    - 树莓派: 
      - 树莓派传感器扩展板: RaspberryPi-Sensor-Board-master/README.md
      - 树莓派电机驱动板: RaspberryPi-MotorDriverBoard/README.md
    - 开源硬件: 
      - Ble-Nano: open_source_hardware/Ble-Nano.md
      - Ble-Uno: open_source_hardware/Ble-Uno.md
      - RF-Nano: open_source_hardware/RF-Nano.md
      - Uno/Mega2560多功能电机驱动板: open_source_hardware/mega2560.md
      - Rgb超声波(RUS-04): open_source_hardware/rgb.md
    - 软件: 
      - MagicBlock: open_source_software/magicblock.md
      - EmakefunApp: open_source_software/EmakefunApp.md
    - 关于我们: about.md
